# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: template.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='template.proto',
  package='GRPCGlobalVariable',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0etemplate.proto\x12\x12GRPCGlobalVariable\"\x07\n\x05\x45mpty\" \n\x04GInt\x12\x0b\n\x03idx\x18\x01 \x01(\x05\x12\x0b\n\x03val\x18\x02 \x01(\x05\"\x15\n\x06IntVal\x12\x0b\n\x03val\x18\x01 \x01(\x05\"!\n\x05GInts\x12\x0b\n\x03idx\x18\x01 \x01(\x05\x12\x0b\n\x03val\x18\x02 \x03(\x05\"\x16\n\x07IntVals\x12\x0b\n\x03val\x18\x01 \x03(\x05\"\'\n\x0cStringWithId\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03val\x18\x02 \x01(\t\"\x16\n\x08StringId\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xcb\x03\n\x16GRPCGlobalVariableTask\x12?\n\x06SetInt\x12\x18.GRPCGlobalVariable.GInt\x1a\x19.GRPCGlobalVariable.Empty\"\x00\x12\x42\n\x06GetInt\x12\x1a.GRPCGlobalVariable.IntVal\x1a\x1a.GRPCGlobalVariable.IntVal\"\x00\x12\x41\n\x07SetInts\x12\x19.GRPCGlobalVariable.GInts\x1a\x19.GRPCGlobalVariable.Empty\"\x00\x12\x42\n\x07GetInts\x12\x18.GRPCGlobalVariable.GInt\x1a\x1b.GRPCGlobalVariable.IntVals\"\x00\x12P\n\x0fSetStringWithId\x12 .GRPCGlobalVariable.StringWithId\x1a\x19.GRPCGlobalVariable.Empty\"\x00\x12S\n\x0fGetStringWithId\x12\x1c.GRPCGlobalVariable.StringId\x1a .GRPCGlobalVariable.StringWithId\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='GRPCGlobalVariable.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=45,
)


_GINT = _descriptor.Descriptor(
  name='GInt',
  full_name='GRPCGlobalVariable.GInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idx', full_name='GRPCGlobalVariable.GInt.idx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='val', full_name='GRPCGlobalVariable.GInt.val', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=79,
)


_INTVAL = _descriptor.Descriptor(
  name='IntVal',
  full_name='GRPCGlobalVariable.IntVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='GRPCGlobalVariable.IntVal.val', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=102,
)


_GINTS = _descriptor.Descriptor(
  name='GInts',
  full_name='GRPCGlobalVariable.GInts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idx', full_name='GRPCGlobalVariable.GInts.idx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='val', full_name='GRPCGlobalVariable.GInts.val', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=137,
)


_INTVALS = _descriptor.Descriptor(
  name='IntVals',
  full_name='GRPCGlobalVariable.IntVals',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='GRPCGlobalVariable.IntVals.val', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=161,
)


_STRINGWITHID = _descriptor.Descriptor(
  name='StringWithId',
  full_name='GRPCGlobalVariable.StringWithId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GRPCGlobalVariable.StringWithId.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='val', full_name='GRPCGlobalVariable.StringWithId.val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=202,
)


_STRINGID = _descriptor.Descriptor(
  name='StringId',
  full_name='GRPCGlobalVariable.StringId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GRPCGlobalVariable.StringId.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=226,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['GInt'] = _GINT
DESCRIPTOR.message_types_by_name['IntVal'] = _INTVAL
DESCRIPTOR.message_types_by_name['GInts'] = _GINTS
DESCRIPTOR.message_types_by_name['IntVals'] = _INTVALS
DESCRIPTOR.message_types_by_name['StringWithId'] = _STRINGWITHID
DESCRIPTOR.message_types_by_name['StringId'] = _STRINGID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:GRPCGlobalVariable.Empty)
  })
_sym_db.RegisterMessage(Empty)

GInt = _reflection.GeneratedProtocolMessageType('GInt', (_message.Message,), {
  'DESCRIPTOR' : _GINT,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:GRPCGlobalVariable.GInt)
  })
_sym_db.RegisterMessage(GInt)

IntVal = _reflection.GeneratedProtocolMessageType('IntVal', (_message.Message,), {
  'DESCRIPTOR' : _INTVAL,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:GRPCGlobalVariable.IntVal)
  })
_sym_db.RegisterMessage(IntVal)

GInts = _reflection.GeneratedProtocolMessageType('GInts', (_message.Message,), {
  'DESCRIPTOR' : _GINTS,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:GRPCGlobalVariable.GInts)
  })
_sym_db.RegisterMessage(GInts)

IntVals = _reflection.GeneratedProtocolMessageType('IntVals', (_message.Message,), {
  'DESCRIPTOR' : _INTVALS,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:GRPCGlobalVariable.IntVals)
  })
_sym_db.RegisterMessage(IntVals)

StringWithId = _reflection.GeneratedProtocolMessageType('StringWithId', (_message.Message,), {
  'DESCRIPTOR' : _STRINGWITHID,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:GRPCGlobalVariable.StringWithId)
  })
_sym_db.RegisterMessage(StringWithId)

StringId = _reflection.GeneratedProtocolMessageType('StringId', (_message.Message,), {
  'DESCRIPTOR' : _STRINGID,
  '__module__' : 'template_pb2'
  # @@protoc_insertion_point(class_scope:GRPCGlobalVariable.StringId)
  })
_sym_db.RegisterMessage(StringId)



_GRPCGLOBALVARIABLETASK = _descriptor.ServiceDescriptor(
  name='GRPCGlobalVariableTask',
  full_name='GRPCGlobalVariable.GRPCGlobalVariableTask',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=229,
  serialized_end=688,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetInt',
    full_name='GRPCGlobalVariable.GRPCGlobalVariableTask.SetInt',
    index=0,
    containing_service=None,
    input_type=_GINT,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetInt',
    full_name='GRPCGlobalVariable.GRPCGlobalVariableTask.GetInt',
    index=1,
    containing_service=None,
    input_type=_INTVAL,
    output_type=_INTVAL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetInts',
    full_name='GRPCGlobalVariable.GRPCGlobalVariableTask.SetInts',
    index=2,
    containing_service=None,
    input_type=_GINTS,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetInts',
    full_name='GRPCGlobalVariable.GRPCGlobalVariableTask.GetInts',
    index=3,
    containing_service=None,
    input_type=_GINT,
    output_type=_INTVALS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetStringWithId',
    full_name='GRPCGlobalVariable.GRPCGlobalVariableTask.SetStringWithId',
    index=4,
    containing_service=None,
    input_type=_STRINGWITHID,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetStringWithId',
    full_name='GRPCGlobalVariable.GRPCGlobalVariableTask.GetStringWithId',
    index=5,
    containing_service=None,
    input_type=_STRINGID,
    output_type=_STRINGWITHID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCGLOBALVARIABLETASK)

DESCRIPTOR.services_by_name['GRPCGlobalVariableTask'] = _GRPCGLOBALVARIABLETASK

# @@protoc_insertion_point(module_scope)
